### ISSUE TITLE
Use Imports instead of Depends

### ISSUE THREAD

**Issue by tmelliott** [StatisticsNZ/demlife#2]
In Description, you should use Imports, and then import functions from dembase as needed.
```
importFrom(dembase, ...)
```

Currently using demlife without loading fails because dembase isn't loaded. e.g., 
```
R> demlife::lifeTable()
```

**Comment by johnrbryant** [comment]
Hmm, I didn't realise the :: didn't work if we use 'depends'. That's useful to know, so thank you for pointing that out! I'm a bit reluctant to drop the 'depends' in case it breaks some existing code - ie people doing 'library(demlife)' and expecting it to load 'dembase' as a side effect. Maybe it would be better if I went through and added 'dembase::' to any functions that 'demlife' uses from 'dembase'? (And I'll completely avoid 'depends' in new packages.)

**Comment by tmelliott** [comment]
Ideally demlife should Import demest - and I have developed a personal preference for using :: instead of Imports - it makes it much more obvious when fns are from another package. One option for existing users would be an onLoad/onAttach (I can never remember exactly which) that prints a message that it no longer loads dembase, so they might need to do that manually. 

Or - something similar to what "library(tidyverse)" does ... https://github.com/tidyverse/tidyverse/blob/master/R/attach.R (which is called here: https://github.com/tidyverse/tidyverse/blob/master/R/zzz.R).

**Comment by johnrbryant** [comment]
onLoad/onAttach is a great idea. I'll do that with 'demest' too (which also 'depends' on dembase). 

Agree about :: being better than importFrom

**Comment by johnrbryant** [comment]
I changed 'dembase' from 'depends' to 'imports' (plus added lots of 'dembase::'). I added an '.onAttach' function, with a message, as you suggested. When you get a chance, can you let me know the changes have solved your problem? Thanks again for the suggestions.

**Comment by tmelliott** [comment]
Yip - that seems to have done the trick :+1:
